export const GET_ERRORS = "GET_ERRORS";
export const GET_VIDEOS = "GET_VIDEOS";
export const GET_SELECTED_VIDEO = "GET_SELECTED_VIDEO";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_RECOMMENDATIONS = "GET_RECOMMENDATIONS";
